'use client';
import { UserProvider } from "@/Context/userAuth";
import { SessionProvider } from "next-auth/react";
import "@/styles/globals.css";


// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang="en">

      <body>
        <UserProvider>
          <SessionProvider>
          {children}
          </SessionProvider>
        </UserProvider>
      </body>
    </html>
  )
}
